# Generated by Django 4.1.2 on 2022-10-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
